### PR TITLE
Implementing a way to revert to original docstrings.

### PR DESCRIPTION
**Pull request by DjebbZ**

### CODE REVIEW

**Comment by DjebbZ** [comment]
fixes #1

**Comment by ericnormand** [comment]
Thanks! This looks good and we do need it.

I wonder if you could loop through all namespaces and vars instead of just the ones in the `docstrings` map. That is, there could be some vars that were changed that we lost track of.

Could you write it to do that instead?

**Comment by DjebbZ** [comment]
I'll give it a try soon hopefully. Happy to help.

**Comment by ericnormand** [comment]
I've merged it because it's good code, even though I'd like to see something that works on all Vars. We can continue to work on it.

**Comment by DjebbZ** [comment]
I'm honored ! I briefly tried to search for the proper solution. Looks like I will need `all-ns` and `ns-map`. But `all-ns` gives a sequence of `clojure.lang.Namespace` objects, I have no idea how to manipulate them. Pretty sure that the solution is something like (in principle) : `(->> (all-ns) (map ns-map) (revert-docs)`. Any pointer ?

**Pull request merged**
